name : CI pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Build Backend
        run: docker build -t jobguard-backend ./backend
      
      - name: Build Frontend
        run: docker build -t jobguard-frontend .